# Generated by Django 4.0.2 on 2022-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_remove_adverb_word_remove_conjunction_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='adjective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='adverb',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='conjunction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='interjection',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='noun',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='preposition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronoun',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='verb',
            field=models.TextField(blank=True),
        ),
    ]
