# Generated by Django 4.0.2 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_word_adjective_alter_word_adverb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(error_messages={'unique': 'This word already exists.'}, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
