# Generated by Django 4.0.2 on 2022-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_word_id_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='adjective',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='adverb',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='conjunction',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='interjection',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='noun',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='preposition',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronoun',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='word',
            name='verb',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
