# Generated by Django 4.0.2 on 2022-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_word_id_alter_word_word'),
        ('account', '0003_remove_collection_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='words',
            field=models.ManyToManyField(to='dictionary.Word'),
        ),
    ]
